### PR TITLE
jupyter_server 2.5.0

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
Options:

- temporarily use the long URL, gated behind a jinja template, e.g. `{% if version == "2.5.0" %}`:
  - https://files.pythonhosted.org/packages/d4/47/55da7a15e1665757c32a07e45fbd2a287071e7f092aff1f863e775065ea4/jupyter_server-2.5.0.tar.gz
- wait a couple hours for CDN or something
  - maybe the bot will make a PR (but seems unlikely)

**Comment by blink1073** [comment]
I'd say wait for things to settle out on the CDN.  This isn't a time-sensitive release.

**Comment by blink1073** [comment]
I can take over babysitting this one.  :smile:

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by blink1073** [comment]
Ugh, weird.  Thanks for the workaround!

**Comment by bollwyvl** [comment]
Yeah, dunno! We'll see what the bot thinks next time around: it is _aware_ of `url: []`, but i don't know it it will try them all  to find the sha.

**Pull request merged**
