### PR TITLE
Unskip py36, pip check, add maintainer

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Since we haven't resolve the `noarch` thing (#24), this uncomments the py36 skip (which may reveal some pypy thing, but we'll deal with that when we get there). Also:
- adds self as maintainer :wave:
- adds pip check, as the list of dependencies is getting rather long, and would prefer to catch these and fix them _before_ releasing
- manually removes `tests` 
  - upstream PR created: https://github.com/jupyter-server/jupyter_server/pull/368
- updates jupyter URL to use `https`

### CODE REVIEW

**Comment by bollwyvl** [comment]
Pypy builds should be up for `anyio` soon... will rekick this at that point:

- pr: https://github.com/conda-forge/anyio-feedstock/pull/18
- merge builds: https://github.com/conda-forge/anyio-feedstock/runs/1636871613

**Comment by bollwyvl** [comment]
also, `tests` are still sneaking in, which i thought i fixed upstream...

**Comment by bollwyvl** [comment]
@conda-forge/jupyter_server ready for review!

**Comment by bollwyvl** [comment]
@conda-forge/jupyter_server I'll be less available today, but checking email occasionally... it would be great to get this in before the hype machine warms up to avoid "doesn't work on py36" support issues.

**Review by blink1073 — APPROVED** [review]
Thanks!

**Comment by bollwyvl** [comment]
Bam! Happy new year!

**Comment by blink1073** [comment]
Happy new year to you too!

**Pull request merged**
