### PR TITLE
add aarch64/ppc64le

### LINKED ISSUE #43: Add support linux aarch64
Currently this is cross-built for osx arm64, but for folks using jetsons or rpis having this installable for Linux aarch64 could be useful.

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

- fixes #43 (maybe)

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
Travis was just `out of space on disk`...

**Comment by bollwyvl** [comment]
Travis/drone all green... will merge once windows finishes on azure...

**Review by Zsailer — APPROVED** [review]

**Comment by bollwyvl** [comment]
@Zsailer we'd never have to do these if we resolved #24 by way of
- https://github.com/jupyter-server/jupyter_server/issues/281
- https://github.com/conda-forge/pywin32-feedstock/issues/34

**Pull request merged**
